"""FastAPI router for the SPX-only decision surface."""

from __future__ import annotations

from fastapi import APIRouter, HTTPException

from models.spx_signal import SPXHealth, SPXSignal
from services.spx_signal_service import spx_signal_service
from services.polygon_client import PolygonAPIError

router = APIRouter(prefix="/spx", tags=["SPX Options"])


@router.get("/signal", response_model=SPXSignal)
async def spx_signal() -> SPXSignal:
    """Return the latest SPX decision, refreshing it when none exists."""
    if spx_signal_service.last_signal is None:
        return await spx_signal_service.evaluate()
    return spx_signal_service.last_signal


@router.post("/signal/refresh", response_model=SPXSignal)
async def spx_signal_refresh() -> SPXSignal:
    return await spx_signal_service.evaluate()


@router.get("/health", response_model=SPXHealth)
def spx_health() -> SPXHealth:
    return spx_signal_service.health()


@router.get("/data-access")
async def spx_data_access() -> dict:
    """One-call entitlement diagnostic for the SPX index feed.

    This endpoint intentionally performs a single small historical request so we can
    verify whether the currently configured Massive/Polygon key can read I:SPX
    minute aggregates without changing trading behavior or substituting another ETF.
    """
    try:
        frame = await spx_signal_service.client.get_aggregates(
            "I:SPX", 5, "minute", 10, 2
        )
        latest = frame.iloc[-1]["timestamp"].isoformat() if not frame.empty else None
        return {
            "provider": "Massive/Polygon",
            "symbol": "I:SPX",
            "status": "available" if not frame.empty else "no_data",
            "bars": int(len(frame)),
            "latest_timestamp": latest,
            "realtime": False,
            "note": "Historical 5-minute aggregate access only; no trade signal is generated by this diagnostic.",
        }
    except PolygonAPIError as exc:
        return {
            "provider": "Massive/Polygon",
            "symbol": "I:SPX",
            "status": "forbidden" if exc.status_code == 403 else "error",
            "bars": 0,
            "latest_timestamp": None,
            "http_status": exc.status_code,
            "realtime": False,
            "message": exc.message,
            "note": "No provider data was substituted and no trade signal was generated.",
        }
    except Exception as exc:
        return {
            "provider": "Massive/Polygon",
            "symbol": "I:SPX",
            "status": "error",
            "bars": 0,
            "latest_timestamp": None,
            "realtime": False,
            "message": str(exc),
            "note": "No provider data was substituted and no trade signal was generated.",
        }


@router.get("/decision")
def spx_decision() -> dict:
    signal = spx_signal_service.last_signal
    if signal is None:
        raise HTTPException(status_code=503, detail="SPX signal not initialized")
    return {
        "symbol": "I:SPX",
        "decision": signal.decision,
        "score": signal.score,
        "confidence": signal.confidence,
        "regime": signal.regime,
        "entry": signal.entry,
        "stop_loss": signal.stop_loss,
        "take_profit_1": signal.take_profit_1,
        "take_profit_2": signal.take_profit_2,
        "reason": signal.reason,
        "kill_switch": signal.kill_switch,
    }
